# Generated by Django 5.0.7 on 2024-07-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_imageprocessid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessid',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
