# Generated by Django 5.0.7 on 2024-07-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_imageprocessid_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprocessid',
            old_name='date',
            new_name='datetime',
        ),
    ]
